### ISSUE TITLE
不支持带#号的表名，panic: Invalid table name

### ISSUE THREAD

**Issue by wittynavier** [liuhr/my2sql#13]
当创建带#表名，然后执行dml操作，再发起生成回滚语句，报错如下
[2021/08/04 16:38:31] [info] events.go:210 start thread to write redo/rollback sql into file
[2021/08/04 16:38:31] [info] events.go:60 start thread 2 to generate redo/rollback sql
[2021/08/04 16:38:31] [info] binlogsyncer.go:144 create BinlogSyncer with config {1113306 mysql 127.0.0.1 3306 root   utf8 false false <nil> false Local false 0 0s 0s 0 false false 0}
[2021/08/04 16:38:31] [info] stats_process.go:166 start thread to analyze statistics from binlog
[2021/08/04 16:38:31] [info] events.go:60 start thread 1 to generate redo/rollback sql
[2021/08/04 16:38:31] [info] binlogsyncer.go:360 begin to sync binlog from position (mysql-bin.000295, 4)
[2021/08/04 16:38:31] [info] repl.go:16 start to get binlog from mysql
[2021/08/04 16:38:31] [info] binlogsyncer.go:777 rotate to (mysql-bin.000295, 4)
panic: Invalid table name

goroutine 36 [running]:
my2sql/sqlbuilder.NewTable(0xc000196060, 0xe, 0xc0000920c0, 0x6, 0x6, 0x6)
        /root/go/src/my2sql/sqlbuilder/table.go:55 +0x314
my2sql/base.GenDeleteSqlsForOneRowsEvent(0xc0001a6000, 0x1e, 0xc000264780, 0xc0000920c0, 0x6, 0x6, 0xc0000aa030, 0x3, 0x3, 0x10100, ...)
        /root/go/src/my2sql/base/sqlgen.go:257 +0x2ae
my2sql/base.GenDeleteSqlsForOneRowsEventRollbackInsert(...)
        /root/go/src/my2sql/base/sqlgen.go:234
my2sql/base.GenForwardRollbackSqlFromBinEvent(0x1, 0x927de0, 0xc000196010)
        /root/go/src/my2sql/base/events.go:137 +0xc12
created by main.main
        /root/go/src/my2sql/main.go:26 +0x205

**Comment by paulmarkyes** [comment]
这个sqlbuilder的错误，你可以在底层源码，把这个判断逻辑，屏蔽掉
