### ISSUE TITLE
panic: Invalid column name in int column

### ISSUE THREAD

**Issue by mhabbyo** [liuhr/my2sql#20]
样例执行过程报这个错误，列名被变更后无法识别到

goroutine 20 [running]:
my2sql/sqlbuilder.DoubleColumn(0xc0002f6920, 0xd, 0x728100, 0x79a0c8, 0xc00054a0f0)
        /root/go/src/my2sql/sqlbuilder/column.go:191 +0xbe
my2sql/base.GetMysqlDataTypeNameAndSqlColumn(0xc0002f6910, 0x7, 0xc0002f6920, 0xd, 0xc00502a0f6, 0x728b13, 0x7, 0x79a0c8, 0xc00054a0f0)
        /root/go/src/my2sql/base/sqlgen.go:81 +0xaa9
my2sql/base.GetSqlFieldsEXpressions(0x3e, 0xc00061f000, 0x3e, 0x40, 0xc000634400, 0x3e, 0x40, 0x0, 0xc0002f6748, 0x1, ...)
        /root/go/src/my2sql/base/sqlgen.go:39 +0x145
my2sql/base.GenForwardRollbackSqlFromBinEvent(0x1, 0x927de0, 0xc000124010)
        /root/go/src/my2sql/base/events.go:83 +0x5fe
created by main.main
        /root/go/src/my2sql/main.go:26 +0x205
panic: Invalid column name in int column

goroutine 21 [running]:
my2sql/sqlbuilder.DoubleColumn(0xc0002f6920, 0xd, 0x728100, 0x79a0c8, 0xc0002cc1e0)
        /root/go/src/my2sql/sqlbuilder/column.go:191 +0xbe
my2sql/base.GetMysqlDataTypeNameAndSqlColumn(0xc0002f6910, 0x7, 0xc0002f6920, 0xd, 0xc00502c0f6, 0x728b13, 0x7, 0x79a0c8, 0xc0002cc1e0)
        /root/go/src/my2sql/base/sqlgen.go:81 +0xaa9
my2sql/base.GetSqlFieldsEXpressions(0x3e, 0xc00061f000, 0x3e, 0x40, 0xc000634400, 0x3e, 0x40, 0x0, 0xc0005f4d80, 0xc00011c0d0, ...)
        /root/go/src/my2sql/base/sqlgen.go:39 +0x145
my2sql/base.GenForwardRollbackSqlFromBinEvent(0x2, 0x927de0, 0xc000124010)
        /root/go/src/my2sql/base/events.go:83 +0x5fe
created by main.main
        /root/go/src/my2sql/main.go:26 +0x20

**Comment by mhabbyo** [comment]
解析的时候，表名已经被变更，伪装成为从库的方式无法解析了。。。
